import type { Database } from "@/lib/types";

export const DB: Database = {
  meta: {
    name: "Bidyapith University",
    bangla: "বিদ্যাপীঠ বিশ্ববিদ্যালয়",
    founded: 1998,
    semester: "Fall 2026",
    admissionCloses: "2026-10-15T23:59:00",
    address: "Bidyapith Campus, Purbachal Sector 9, Dhaka 1229",
    phone: "+880 2 8415 2200",
    email: "info@bidyapith.edu.bd",
  },

  stats: [
    { label: "Students enrolled", value: 9240, suffix: "" },
    { label: "Faculty members", value: 312, suffix: "" },
    { label: "Courses offered", value: 486, suffix: "" },
    { label: "Degree programs", value: 34, suffix: "" },
    { label: "Graduate employment", value: 94, suffix: "%" },
    { label: "Research papers, 2025", value: 218, suffix: "" },
  ],

  enrolment: [
    { label: "Engineering", value: 3120, color: "#2ED3A7" },
    { label: "Business", value: 2140, color: "#9B8CFF" },
    { label: "Science", value: 1680, color: "#FFB454" },
    { label: "Arts & Humanities", value: 1180, color: "#6FD8FF" },
    { label: "Health Sciences", value: 620, color: "#FF7E9D" },
    { label: "Law", value: 500, color: "#C6BCFF" },
  ],

  intake: [
    { label: "'19", value: 1180 },
    { label: "'20", value: 940 },
    { label: "'21", value: 1320 },
    { label: "'22", value: 1560 },
    { label: "'23", value: 1740 },
    { label: "'24", value: 1980 },
    { label: "'25", value: 2260 },
    { label: "'26", value: 2480 },
  ],

  registrations: [
    { label: "Sp 24", value: 8.2 },
    { label: "Su 24", value: 5.1 },
    { label: "Fa 24", value: 8.9 },
    { label: "Sp 25", value: 9.4 },
    { label: "Su 25", value: 5.8 },
    { label: "Fa 25", value: 10.2 },
    { label: "Sp 26", value: 11.1 },
    { label: "Fa 26", value: 12.4 },
  ],

  seats: [
    { label: "B.Sc. in Computer Science", filled: 178, total: 180 },
    { label: "BBA in Finance", filled: 132, total: 160 },
    { label: "B.Sc. in Civil Engineering", filled: 96, total: 140 },
    { label: "LL.B. (Honours)", filled: 54, total: 90 },
    { label: "B.Pharm (Professional)", filled: 71, total: 80 },
  ],

  departments: [
    { id: "cse", name: "Computer Science & Engineering", school: "Engineering", head: "Prof. Dr. Ayesha Rahman", programs: 4, courses: 86, faculty: 42 },
    { id: "eee", name: "Electrical & Electronic Engineering", school: "Engineering", head: "Prof. Dr. Kamal Hossain", programs: 3, courses: 64, faculty: 31 },
    { id: "civ", name: "Civil Engineering", school: "Engineering", head: "Dr. Nusrat Jahan", programs: 3, courses: 58, faculty: 27 },
    { id: "bba", name: "Business Administration", school: "Business", head: "Prof. Dr. Shahriar Kabir", programs: 6, courses: 74, faculty: 38 },
    { id: "eco", name: "Economics", school: "Business", head: "Dr. Farhana Islam", programs: 2, courses: 41, faculty: 19 },
    { id: "phy", name: "Physics", school: "Science", head: "Prof. Dr. Mahfuz Alam", programs: 3, courses: 47, faculty: 22 },
    { id: "mat", name: "Mathematics", school: "Science", head: "Dr. Tanvir Ahmed", programs: 2, courses: 39, faculty: 18 },
    { id: "eng", name: "English & Literature", school: "Arts & Humanities", head: "Dr. Sadia Noor", programs: 3, courses: 44, faculty: 21 },
    { id: "law", name: "Law & Justice", school: "Law", head: "Prof. Dr. Rezaul Karim", programs: 2, courses: 33, faculty: 16 },
    { id: "pha", name: "Pharmacy", school: "Health Sciences", head: "Dr. Mitali Saha", programs: 2, courses: 36, faculty: 20 },
  ],

  programs: [
    { code: "BSC-CSE", name: "B.Sc. in Computer Science & Engineering", dept: "cse", school: "Engineering", level: "Undergraduate", credits: 156, years: 4, seats: 180, filled: 178, tuition: 68000, tag: "Most applied",
      about: "A four-year programme built around systems, data and software engineering, with a two-semester industry capstone in the final year.",
      highlights: ["Data Structures & Algorithms", "Distributed Systems", "Machine Learning", "Industry capstone (2 semesters)"] },
    { code: "BSC-EEE", name: "B.Sc. in Electrical & Electronic Engineering", dept: "eee", school: "Engineering", level: "Undergraduate", credits: 160, years: 4, seats: 140, filled: 118, tuition: 66000, tag: "",
      about: "Power, electronics and embedded systems, taught in labs that mirror the national grid and modern manufacturing floors.",
      highlights: ["Power Systems", "VLSI Design", "Embedded & IoT", "Renewable energy lab"] },
    { code: "BSC-CIV", name: "B.Sc. in Civil Engineering", dept: "civ", school: "Engineering", level: "Undergraduate", credits: 158, years: 4, seats: 140, filled: 96, tuition: 64000, tag: "Seats open",
      about: "Structural, geotechnical and transport engineering with field study weeks on live infrastructure projects around Dhaka.",
      highlights: ["Structural Analysis", "Geotechnics", "Transportation Planning", "Site study weeks"] },
    { code: "BBA-FIN", name: "BBA in Finance", dept: "bba", school: "Business", level: "Undergraduate", credits: 132, years: 4, seats: 160, filled: 132, tuition: 58000, tag: "",
      about: "Corporate finance, capital markets and financial analytics, with a Bloomberg-equipped trading room and a required internship.",
      highlights: ["Corporate Finance", "Investment Analysis", "Financial Modelling", "12-week internship"] },
    { code: "BBA-MKT", name: "BBA in Marketing", dept: "bba", school: "Business", level: "Undergraduate", credits: 132, years: 4, seats: 150, filled: 121, tuition: 56000, tag: "",
      about: "Brand strategy and consumer research for a market that moves fast, taught largely through live client briefs.",
      highlights: ["Consumer Behaviour", "Digital Marketing", "Brand Management", "Live client projects"] },
    { code: "BSC-PHY", name: "B.Sc. in Physics", dept: "phy", school: "Science", level: "Undergraduate", credits: 144, years: 4, seats: 90, filled: 61, tuition: 42000, tag: "Seats open",
      about: "Classical and quantum physics with a research thesis, feeding into national and international graduate programmes.",
      highlights: ["Quantum Mechanics", "Computational Physics", "Astrophysics elective", "Final-year thesis"] },
    { code: "BA-ENG", name: "B.A. (Hons) in English", dept: "eng", school: "Arts & Humanities", level: "Undergraduate", credits: 128, years: 4, seats: 120, filled: 88, tuition: 38000, tag: "",
      about: "Literature, linguistics and translation studies, with a standing workshop in Bangla–English literary translation.",
      highlights: ["Postcolonial Literature", "Linguistics", "Translation workshop", "Creative writing"] },
    { code: "LLB-HON", name: "LL.B. (Honours)", dept: "law", school: "Law", level: "Undergraduate", credits: 140, years: 4, seats: 90, filled: 54, tuition: 52000, tag: "Seats open",
      about: "Constitutional, corporate and human-rights law, with a moot court that competes nationally every spring.",
      highlights: ["Constitutional Law", "Corporate Law", "Moot court", "Legal aid clinic"] },
    { code: "BPH-PRO", name: "B.Pharm (Professional)", dept: "pha", school: "Health Sciences", level: "Undergraduate", credits: 164, years: 5, seats: 80, filled: 71, tuition: 74000, tag: "Closing soon",
      about: "A five-year professional degree accredited by the Pharmacy Council of Bangladesh, including hospital rotations.",
      highlights: ["Pharmacology", "Pharmaceutical Chemistry", "Hospital rotations", "PCB accredited"] },
    { code: "MSC-CSE", name: "M.Sc. in Computer Science", dept: "cse", school: "Engineering", level: "Graduate", credits: 36, years: 2, seats: 60, filled: 44, tuition: 48000, tag: "",
      about: "A research-track master's for working developers, with evening classes and a supervised thesis.",
      highlights: ["Advanced Algorithms", "Cloud Architecture", "Research thesis", "Evening schedule"] },
    { code: "MBA-EXE", name: "Executive MBA", dept: "bba", school: "Business", level: "Graduate", credits: 48, years: 2, seats: 70, filled: 58, tuition: 82000, tag: "Weekend",
      about: "A weekend MBA for mid-career managers, taught in cohorts of thirty with a company-based consulting project.",
      highlights: ["Strategy", "Operations", "Leadership lab", "Consulting project"] },
    { code: "MA-ECO", name: "M.A. in Economics", dept: "eco", school: "Business", level: "Graduate", credits: 40, years: 2, seats: 50, filled: 31, tuition: 40000, tag: "Seats open",
      about: "Applied econometrics and development economics, with access to national survey micro-data.",
      highlights: ["Econometrics", "Development Economics", "Policy analysis", "Micro-data access"] },
  ],

  courses: [
    { code: "CSE-2201", title: "Data Structures & Algorithms", dept: "cse", credits: 3, level: 200, semester: "Fall", prereq: "CSE-1101", instructor: "Prof. Dr. Ayesha Rahman", seats: 60, taken: 58 },
    { code: "CSE-3105", title: "Database Systems", dept: "cse", credits: 3, level: 300, semester: "Fall", prereq: "CSE-2201", instructor: "Dr. Tanvir Ahmed", seats: 55, taken: 41 },
    { code: "CSE-3210", title: "Operating Systems", dept: "cse", credits: 3, level: 300, semester: "Spring", prereq: "CSE-2201", instructor: "Dr. Sabbir Rahman", seats: 55, taken: 55 },
    { code: "CSE-4108", title: "Machine Learning", dept: "cse", credits: 3, level: 400, semester: "Fall", prereq: "MAT-2103", instructor: "Dr. Nafisa Haque", seats: 45, taken: 45 },
    { code: "CSE-4210", title: "Distributed Systems", dept: "cse", credits: 3, level: 400, semester: "Spring", prereq: "CSE-3210", instructor: "Prof. Dr. Ayesha Rahman", seats: 40, taken: 27 },
    { code: "EEE-2104", title: "Circuit Analysis II", dept: "eee", credits: 3, level: 200, semester: "Spring", prereq: "EEE-1104", instructor: "Prof. Dr. Kamal Hossain", seats: 50, taken: 44 },
    { code: "EEE-3301", title: "Power System Engineering", dept: "eee", credits: 3, level: 300, semester: "Fall", prereq: "EEE-2104", instructor: "Dr. Rubel Mia", seats: 45, taken: 33 },
    { code: "EEE-4205", title: "VLSI Design", dept: "eee", credits: 3, level: 400, semester: "Spring", prereq: "EEE-3202", instructor: "Dr. Rubel Mia", seats: 35, taken: 19 },
    { code: "CIV-2107", title: "Structural Mechanics", dept: "civ", credits: 3, level: 200, semester: "Fall", prereq: "CIV-1102", instructor: "Dr. Nusrat Jahan", seats: 50, taken: 36 },
    { code: "CIV-3204", title: "Geotechnical Engineering", dept: "civ", credits: 4, level: 300, semester: "Spring", prereq: "CIV-2107", instructor: "Dr. Imran Chowdhury", seats: 40, taken: 28 },
    { code: "BBA-1101", title: "Principles of Management", dept: "bba", credits: 3, level: 100, semester: "Fall", prereq: "—", instructor: "Prof. Dr. Shahriar Kabir", seats: 80, taken: 76 },
    { code: "BBA-3104", title: "Corporate Finance", dept: "bba", credits: 3, level: 300, semester: "Fall", prereq: "BBA-2103", instructor: "Dr. Sharmin Akter", seats: 65, taken: 61 },
    { code: "BBA-3208", title: "Consumer Behaviour", dept: "bba", credits: 3, level: 300, semester: "Spring", prereq: "BBA-2201", instructor: "Dr. Rakib Hasan", seats: 60, taken: 39 },
    { code: "ECO-2102", title: "Intermediate Microeconomics", dept: "eco", credits: 3, level: 200, semester: "Spring", prereq: "ECO-1101", instructor: "Dr. Farhana Islam", seats: 55, taken: 34 },
    { code: "ECO-4103", title: "Econometrics", dept: "eco", credits: 4, level: 400, semester: "Fall", prereq: "MAT-2103", instructor: "Dr. Farhana Islam", seats: 40, taken: 40 },
    { code: "PHY-2201", title: "Quantum Mechanics I", dept: "phy", credits: 4, level: 200, semester: "Fall", prereq: "PHY-1202", instructor: "Prof. Dr. Mahfuz Alam", seats: 40, taken: 22 },
    { code: "PHY-3106", title: "Computational Physics", dept: "phy", credits: 3, level: 300, semester: "Spring", prereq: "PHY-2201", instructor: "Dr. Anisur Rahman", seats: 35, taken: 18 },
    { code: "MAT-2103", title: "Linear Algebra & Statistics", dept: "mat", credits: 3, level: 200, semester: "Fall", prereq: "MAT-1102", instructor: "Dr. Tanvir Ahmed", seats: 90, taken: 84 },
    { code: "MAT-3204", title: "Numerical Methods", dept: "mat", credits: 3, level: 300, semester: "Spring", prereq: "MAT-2103", instructor: "Dr. Sumaiya Binte Karim", seats: 60, taken: 37 },
    { code: "ENG-2105", title: "Postcolonial Literature", dept: "eng", credits: 3, level: 200, semester: "Fall", prereq: "ENG-1103", instructor: "Dr. Sadia Noor", seats: 45, taken: 31 },
    { code: "ENG-3202", title: "Translation Workshop", dept: "eng", credits: 3, level: 300, semester: "Spring", prereq: "ENG-2105", instructor: "Dr. Sadia Noor", seats: 30, taken: 30 },
    { code: "LAW-2201", title: "Constitutional Law", dept: "law", credits: 4, level: 200, semester: "Spring", prereq: "LAW-1102", instructor: "Prof. Dr. Rezaul Karim", seats: 50, taken: 29 },
    { code: "LAW-4102", title: "Corporate & Securities Law", dept: "law", credits: 3, level: 400, semester: "Fall", prereq: "LAW-3105", instructor: "Barrister Nazmul Huda", seats: 40, taken: 24 },
    { code: "PHA-3105", title: "Pharmacology I", dept: "pha", credits: 4, level: 300, semester: "Fall", prereq: "PHA-2104", instructor: "Dr. Mitali Saha", seats: 40, taken: 38 },
    { code: "PHA-4201", title: "Clinical Pharmacy Practice", dept: "pha", credits: 4, level: 400, semester: "Spring", prereq: "PHA-3105", instructor: "Dr. Mitali Saha", seats: 32, taken: 26 },
  ],

  faculty: [
    { name: "Prof. Dr. Ayesha Rahman", dept: "cse", role: "Professor & Head", field: "Distributed systems, applied ML", email: "ayesha.rahman@bidyapith.edu.bd", office: "Sun & Tue, 2–4 PM", since: 2009, papers: 47,
      bio: "Leads the systems research group and supervises the CSE capstone track. Previously a research engineer in Singapore, now working on scheduling for low-bandwidth campus networks." },
    { name: "Prof. Dr. Kamal Hossain", dept: "eee", role: "Professor & Head", field: "Power systems, grid stability", email: "kamal.hossain@bidyapith.edu.bd", office: "Mon & Wed, 11 AM–1 PM", since: 2006, papers: 63,
      bio: "Advises the national grid modernisation committee and runs the renewable energy lab. His students have twice won the IEEE regional power design award." },
    { name: "Dr. Nusrat Jahan", dept: "civ", role: "Associate Professor & Head", field: "Structural engineering", email: "nusrat.jahan@bidyapith.edu.bd", office: "Tue & Thu, 10 AM–12 PM", since: 2013, papers: 29,
      bio: "Specialises in earthquake-resilient structures for dense urban housing, with field studies across Dhaka's older neighbourhoods." },
    { name: "Prof. Dr. Shahriar Kabir", dept: "bba", role: "Professor & Dean, Business", field: "Strategy, organisational behaviour", email: "shahriar.kabir@bidyapith.edu.bd", office: "Sun & Wed, 3–5 PM", since: 2004, papers: 51,
      bio: "Dean of the School of Business and architect of the Executive MBA. Consults for three of the country's largest manufacturing groups." },
    { name: "Dr. Farhana Islam", dept: "eco", role: "Associate Professor & Head", field: "Development economics", email: "farhana.islam@bidyapith.edu.bd", office: "Mon & Thu, 1–3 PM", since: 2014, papers: 34,
      bio: "Works with national survey micro-data on rural credit access, and teaches the econometrics sequence." },
    { name: "Prof. Dr. Mahfuz Alam", dept: "phy", role: "Professor & Head", field: "Quantum optics", email: "mahfuz.alam@bidyapith.edu.bd", office: "Tue & Thu, 2–4 PM", since: 2007, papers: 58,
      bio: "Runs the optics laboratory and mentors students into international PhD programmes. Co-author of a widely used undergraduate mechanics text." },
    { name: "Dr. Sadia Noor", dept: "eng", role: "Associate Professor & Head", field: "Postcolonial literature, translation", email: "sadia.noor@bidyapith.edu.bd", office: "Sun & Tue, 11 AM–1 PM", since: 2015, papers: 22,
      bio: "Translates contemporary Bangla fiction into English and directs the university's annual literary festival." },
    { name: "Prof. Dr. Rezaul Karim", dept: "law", role: "Professor & Head", field: "Constitutional law", email: "rezaul.karim@bidyapith.edu.bd", office: "Wed, 10 AM–1 PM", since: 2011, papers: 41,
      bio: "Coaches the moot court team and writes on judicial independence. Practised before the High Court Division for nine years." },
    { name: "Dr. Mitali Saha", dept: "pha", role: "Associate Professor & Head", field: "Clinical pharmacology", email: "mitali.saha@bidyapith.edu.bd", office: "Mon & Wed, 9–11 AM", since: 2016, papers: 26,
      bio: "Coordinates hospital rotations with three partner hospitals and researches antibiotic stewardship in outpatient care." },
    { name: "Dr. Tanvir Ahmed", dept: "mat", role: "Associate Professor & Head", field: "Applied mathematics", email: "tanvir.ahmed@bidyapith.edu.bd", office: "Sun & Thu, 2–4 PM", since: 2012, papers: 31,
      bio: "Teaches the linear algebra sequence taken by every engineering student, and researches numerical methods for fluid models." },
    { name: "Dr. Nafisa Haque", dept: "cse", role: "Assistant Professor", field: "Machine learning, NLP", email: "nafisa.haque@bidyapith.edu.bd", office: "Tue & Thu, 3–5 PM", since: 2019, papers: 18,
      bio: "Builds Bangla language models and leads the undergraduate research seminar in applied ML." },
    { name: "Dr. Sharmin Akter", dept: "bba", role: "Assistant Professor", field: "Corporate finance", email: "sharmin.akter@bidyapith.edu.bd", office: "Mon & Wed, 2–4 PM", since: 2018, papers: 15,
      bio: "Runs the trading room simulation and researches capital structure among listed firms in Dhaka." },
  ],

  notices: [
    { id: 1, title: "Fall 2026 course registration opens", date: "2026-09-08", type: "Academic", pinned: true, body: "Registration for Fall 2026 opens at 9:00 AM. Advisory clearance must be completed before you can add courses; students with outstanding dues will be blocked at the payment step." },
    { id: 2, title: "Mid-term examination schedule published", date: "2026-09-04", type: "Exam", pinned: true, body: "The mid-term schedule for all undergraduate programmes is now available on the student portal. Seat plans go up 48 hours before each exam." },
    { id: 3, title: "Spring 2026 results released", date: "2026-08-28", type: "Result", pinned: false, body: "Grades and GPA for Spring 2026 have been published. Re-scrutiny applications close on 10 September." },
    { id: 4, title: "Bidyapith Tech Fest 2026 — call for teams", date: "2026-08-22", type: "Event", pinned: false, body: "Registration is open for the hackathon, robotics and case-solving tracks. Teams of up to four; cross-department teams are encouraged." },
    { id: 5, title: "Tuition instalment deadline: 20 September", date: "2026-08-18", type: "Payment", pinned: false, body: "The second instalment for Fall 2026 is due on 20 September. Pay through bKash or card from the student portal; a late fee applies from 21 September." },
    { id: 6, title: "Library extends hours during exam weeks", date: "2026-08-11", type: "Notice", pinned: false, body: "The central library stays open until 1:00 AM through the mid-term and final examination periods. Bring your student ID for entry after 10 PM." },
    { id: 7, title: "Scholarship applications for merit awards", date: "2026-08-05", type: "Academic", pinned: false, body: "Students with a CGPA of 3.75 or above may apply for the Vice-Chancellor's merit award. Applications close 25 September." },
    { id: 8, title: "Campus shuttle route change from 1 September", date: "2026-07-30", type: "Notice", pinned: false, body: "The Uttara shuttle now stops at Sector 4 instead of Sector 7. Timings are unchanged." },
  ],

  events: [
    { title: "Admission open day", date: "2026-09-20", place: "Central Auditorium", time: "10:00 AM" },
    { title: "Bidyapith Tech Fest", date: "2026-10-02", place: "Engineering Quad", time: "9:00 AM" },
    { title: "Convocation 2026", date: "2026-11-14", place: "University Ground", time: "3:00 PM" },
    { title: "Research symposium", date: "2026-11-28", place: "Library Hall", time: "11:00 AM" },
  ],

  admissionSteps: [
    { title: "Create an account", text: "Register with your email or Google account and verify your address. This becomes your applicant portal." },
    { title: "Fill in the application", text: "Add academic history, upload your SSC and HSC transcripts, and pick up to three programmes in order of preference." },
    { title: "Pay the application fee", text: "Pay ৳1,000 through bKash or card. Your payment is verified against the gateway before the application is queued." },
    { title: "Sit the admission test", text: "Written test on campus, followed by a short viva for shortlisted candidates. Admit cards are issued on the portal." },
    { title: "Confirm your seat", text: "Accept the offer and pay the first instalment within seven days to lock your seat and get your student ID." },
  ],

  keyDates: [
    { label: "Application opens", date: "20 August 2026", status: "done" },
    { label: "Application closes", date: "15 October 2026", status: "live" },
    { label: "Admission test", date: "25 October 2026", status: "next" },
    { label: "Results published", date: "05 November 2026", status: "next" },
    { label: "Seat confirmation ends", date: "15 November 2026", status: "next" },
    { label: "Classes begin", date: "01 December 2026", status: "next" },
  ],

  fees: [
    { program: "B.Sc. in Computer Science & Engineering", admission: 25000, perCredit: 3200, semester: 68000, total: 1116000 },
    { program: "B.Sc. in Electrical & Electronic Engineering", admission: 25000, perCredit: 3100, semester: 66000, total: 1084000 },
    { program: "B.Sc. in Civil Engineering", admission: 25000, perCredit: 3000, semester: 64000, total: 1052000 },
    { program: "BBA in Finance", admission: 20000, perCredit: 2600, semester: 58000, total: 884000 },
    { program: "LL.B. (Honours)", admission: 20000, perCredit: 2400, semester: 52000, total: 812000 },
    { program: "B.Pharm (Professional)", admission: 30000, perCredit: 3400, semester: 74000, total: 1420000 },
  ],

  scholarships: [
    { name: "Merit award", cover: "Up to 100%", who: "GPA 5.00 in both SSC and HSC, or CGPA 3.90+ at Bidyapith.", accent: "jade" },
    { name: "Need-based grant", cover: "25–60%", who: "Assessed on family income with documentation, renewed each year.", accent: "gold" },
    { name: "Freedom fighter quota", cover: "50%", who: "Children and grandchildren of certified freedom fighters.", accent: "orchid" },
    { name: "Sibling & alumni waiver", cover: "15%", who: "A sibling currently enrolled, or a parent who graduated from Bidyapith.", accent: "rose" },
  ],

  faqs: [
    { q: "Can I apply to more than one programme?", a: "Yes. You may list up to three programmes in order of preference on a single application, and you pay the fee once." },
    { q: "How do I pay the application fee?", a: "From the applicant portal, through bKash or any Visa/Mastercard. The portal confirms your payment only after the gateway verifies it, so never pay outside the portal." },
    { q: "What happens if I miss the admission test?", a: "Contact the admission office within 48 hours with documentation. One make-up sitting is arranged before results are published, at the registrar's discretion." },
    { q: "Are transcripts required at the time of application?", a: "Scanned copies are enough to apply. Originals are verified when you confirm your seat, and your admission is provisional until then." },
    { q: "Can I transfer credits from another university?", a: "Up to 40% of your programme credits may be transferred if the courses match ours in content and credit hours. The department head reviews each course." },
    { q: "Is there accommodation on campus?", a: "Yes, separate halls for men and women, allocated by distance from home and year of study. Apply through the portal after you confirm your seat." },
  ],

  voices: [
    { name: "Rifat Chowdhury", meta: "CSE, Class of 2025 · Engineer at Brain Station 23", quote: "The capstone was two full semesters with a real client. I walked into my first interview with a system I had actually shipped, not a slide deck.", av: 1 },
    { name: "Anika Tabassum", meta: "BBA Finance, Class of 2024 · Analyst at IDLC", quote: "Registration used to mean a queue in the admin building. Now it is four clicks and my advisor signs off from her phone.", av: 2 },
    { name: "Shakib Al Noman", meta: "LL.B., Class of 2026 · Moot court captain", quote: "Our moot team reached the national final in my third year. The faculty treated us like colleagues, not students to be marked.", av: 3 },
  ],

  milestones: [
    { year: "1998", title: "Bidyapith opens", text: "Founded with two departments and 240 students in a rented building in Dhanmondi." },
    { year: "2005", title: "Purbachal campus", text: "Moved to a purpose-built 22-acre campus with the first engineering laboratories." },
    { year: "2012", title: "Graduate school", text: "Master's programmes launched across Engineering and Business, with an evening schedule for working professionals." },
    { year: "2019", title: "Research centre", text: "The Centre for Applied Research opened, funding 40 student projects in its first year." },
    { year: "2026", title: "One digital campus", text: "Admission, registration, attendance, results and fees moved onto a single system used by every department." },
  ],

  leadership: [
    { name: "Prof. Dr. Anwar Hossain", role: "Vice-Chancellor", note: "Physicist, twenty-two years in higher education administration.", av: 1 },
    { name: "Prof. Dr. Shahriar Kabir", role: "Pro Vice-Chancellor", note: "Dean of Business and architect of the Executive MBA.", av: 2 },
    { name: "Md. Jahangir Alam", role: "Registrar", note: "Runs admissions, records and the academic calendar.", av: 3 },
    { name: "Dr. Farzana Rahman", role: "Dean of Students", note: "Oversees halls, clubs, counselling and student welfare.", av: 4 },
  ],
};
