import type { Database } from "@/lib/types";

export const DB: Database = {
  meta: {
    name: "Bidyapith University",
    bangla: "বিদ্যাপীঠ বিশ্ববিদ্যালয়",
    founded: 1998,
    semester: "Fall 2026",
    admissionCloses: "2026-10-15T23:59:00",
    address: "Bidyapith Campus, Purbachal Sector 9, Dhaka 1229",
    phone: "+880 2 8415 2200",
    email: "info@bidyapith.edu.bd",
  },

  stats: [
    { label: "Students enrolled", value: 9240, suffix: "" },
    { label: "Faculty members", value: 312, suffix: "" },
    { label: "Courses offered", value: 486, suffix: "" },
    { label: "Degree programs", value: 34, suffix: "" },
    { label: "Graduate employment", value: 94, suffix: "%" },
    { label: "Research papers, 2025", value: 218, suffix: "" },
  ],

  enrolment: [
    { label: "Engineering", value: 3120, color: "#2ED3A7" },
    { label: "Business", value: 2140, color: "#9B8CFF" },
    { label: "Science", value: 1680, color: "#FFB454" },
    { label: "Arts & Humanities", value: 1180, color: "#6FD8FF" },
    { label: "Health Sciences", value: 620, color: "#FF7E9D" },
    { label: "Law", value: 500, color: "#C6BCFF" },
  ],

  intake: [
    { label: "'19", value: 1180 },
    { label: "'20", value: 940 },
    { label: "'21", value: 1320 },
    { label: "'22", value: 1560 },
    { label: "'23", value: 1740 },
    { label: "'24", value: 1980 },
    { label: "'25", value: 2260 },
    { label: "'26", value: 2480 },
  ],

  registrations: [
    { label: "Sp 24", value: 8.2 },
    { label: "Su 24", value: 5.1 },
    { label: "Fa 24", value: 8.9 },
    { label: "Sp 25", value: 9.4 },
    { label: "Su 25", value: 5.8 },
    { label: "Fa 25", value: 10.2 },
    { label: "Sp 26", value: 11.1 },
    { label: "Fa 26", value: 12.4 },
  ],

  seats: [
    { label: "B.Sc. in Computer Science", filled: 178, total: 180 },
    { label: "BBA in Finance", filled: 132, total: 160 },
    { label: "B.Sc. in Civil Engineering", filled: 96, total: 140 },
    { label: "LL.B. (Honours)", filled: 54, total: 90 },
    { label: "B.Pharm (Professional)", filled: 71, total: 80 },
  ],

  departments: [
    { id: "cse", name: "Computer Science & Engineering", school: "Engineering", head: "Prof. Dr. Ayesha Rahman", programs: 4, courses: 86, faculty: 42 },
    { id: "eee", name: "Electrical & Electronic Engineering", school: "Engineering", head: "Prof. Dr. Kamal Hossain", programs: 3, courses: 64, faculty: 31 },
    { id: "civ", name: "Civil & Environmental Engineering", school: "Engineering", head: "Dr. Nusrat Jahan", programs: 3, courses: 58, faculty: 27 },
    { id: "bba", name: "Business Administration", school: "Business", head: "Prof. Dr. Shahriar Kabir", programs: 6, courses: 74, faculty: 38 },
    { id: "eco", name: "Economics", school: "Business", head: "Dr. Farhana Islam", programs: 2, courses: 41, faculty: 19 },
    { id: "phy", name: "Physics", school: "Science", head: "Prof. Dr. Mahfuz Alam", programs: 3, courses: 47, faculty: 22 },
    { id: "mat", name: "Mathematics", school: "Science", head: "Dr. Tanvir Ahmed", programs: 2, courses: 39, faculty: 18 },
    { id: "eng", name: "English & Literature", school: "Arts & Humanities", head: "Dr. Sadia Noor", programs: 3, courses: 44, faculty: 21 },
    { id: "law", name: "Law & Justice", school: "Law", head: "Prof. Dr. Rezaul Karim", programs: 2, courses: 33, faculty: 16 },
    { id: "pha", name: "Pharmacy & Health Sciences", school: "Health Sciences", head: "Dr. Mitali Saha", programs: 2, courses: 36, faculty: 20 },
  ],

  programs: [
    { code: "BSC-CSE", name: "B.Sc. in Computer Science & Engineering", dept: "cse", school: "Engineering", level: "Undergraduate", credits: 140, years: 4, seats: 180, filled: 178, tuition: 68000, tag: "Most applied",
      about: "A four-year programme built around algorithms, software engineering, databases, and AI with a final-year industry capstone.",
      highlights: ["Data Structures & Algorithms", "Distributed Systems", "Machine Learning & AI", "Industry Capstone Track"] },
    { code: "BSC-EEE", name: "B.Sc. in Electrical & Electronic Engineering", dept: "eee", school: "Engineering", level: "Undergraduate", credits: 144, years: 4, seats: 140, filled: 118, tuition: 66000, tag: "",
      about: "Power systems, renewable grids, and VLSI design taught in advanced semiconductor and power laboratories.",
      highlights: ["Power Systems Engineering", "VLSI Design", "Embedded Systems & IoT", "Smart Grid Technologies"] },
    { code: "BSC-CIV", name: "B.Sc. in Civil Engineering", dept: "civ", school: "Engineering", level: "Undergraduate", credits: 142, years: 4, seats: 140, filled: 96, tuition: 64000, tag: "Seats open",
      about: "Structural analysis, geotechnical engineering, and environmental infrastructure management with fieldwork.",
      highlights: ["Structural Mechanics", "Geotechnics", "Transportation Planning", "Earthquake-Resilient Design"] },
    { code: "BBA-GEN", name: "Bachelor of Business Administration", dept: "bba", school: "Business", level: "Undergraduate", credits: 128, years: 4, seats: 160, filled: 132, tuition: 58000, tag: "Popular",
      about: "Corporate finance, marketing analytics, and supply chain management with Bloomberg trading room access.",
      highlights: ["Corporate Finance", "Digital Marketing", "Financial Modelling", "12-week Mandatory Internship"] },
    { code: "BSS-ECO", name: "B.S.S. in Economics", dept: "eco", school: "Business", level: "Undergraduate", credits: 126, years: 4, seats: 90, filled: 65, tuition: 48000, tag: "",
      about: "Applied micro-econometrics, development economics, and macroeconomic policy analysis.",
      highlights: ["Applied Econometrics", "Development Economics", "Macroeconomic Modelling", "Policy Analysis Lab"] },
    { code: "BSC-MAT", name: "B.Sc. in Mathematics", dept: "mat", school: "Science", level: "Undergraduate", credits: 128, years: 4, seats: 80, filled: 58, tuition: 42000, tag: "Seats open",
      about: "Pure and applied mathematics, numerical optimization, dynamical systems, and data science foundations.",
      highlights: ["Linear Algebra", "Numerical Analysis", "Probability & Statistics", "Mathematical Modelling"] },
    { code: "BSC-PHY", name: "B.Sc. in Physics", dept: "phy", school: "Science", level: "Undergraduate", credits: 130, years: 4, seats: 90, filled: 61, tuition: 42000, tag: "",
      about: "Classical and quantum physics with a research thesis, optical laboratories, and computational modeling.",
      highlights: ["Quantum Mechanics", "Computational Physics", "Quantum Optics", "Undergraduate Thesis"] },
    { code: "BA-ENG", name: "B.A. (Hons) in English Literature", dept: "eng", school: "Arts & Humanities", level: "Undergraduate", credits: 124, years: 4, seats: 120, filled: 88, tuition: 38000, tag: "",
      about: "World literature, critical theory, linguistics, and literary translation workshops.",
      highlights: ["Postcolonial Literature", "Translation Workshop", "Applied Linguistics", "Creative Writing"] },
    { code: "LLB-HON", name: "LL.B. (Honours)", dept: "law", school: "Law", level: "Undergraduate", credits: 136, years: 4, seats: 90, filled: 54, tuition: 52000, tag: "Seats open",
      about: "Constitutional, corporate, and international human rights law with an active moot court society.",
      highlights: ["Constitutional Law", "Corporate & Securities Law", "Moot Court Practice", "Legal Aid Clinic"] },
    { code: "BPH-PRO", name: "Bachelor of Pharmacy (Professional)", dept: "pha", school: "Health Sciences", level: "Undergraduate", credits: 160, years: 5, seats: 80, filled: 71, tuition: 74000, tag: "PCB Accredited",
      about: "A five-year professional pharmacy degree accredited by the Pharmacy Council of Bangladesh.",
      highlights: ["Pharmacology & Therapeutics", "Pharmaceutical Chemistry", "Hospital Rotations", "Biopharmaceutics"] },
    { code: "MSC-CSE", name: "M.Sc. in Computer Science & Engineering", dept: "cse", school: "Engineering", level: "Graduate", credits: 36, years: 2, seats: 60, filled: 44, tuition: 48000, tag: "Evening",
      about: "A graduate research degree focusing on distributed cloud systems, machine learning, and security.",
      highlights: ["Advanced Algorithms", "Cloud Architecture", "Research Thesis", "Evening/Weekend Schedule"] },
    { code: "MBA-EXE", name: "Executive MBA", dept: "bba", school: "Business", level: "Graduate", credits: 48, years: 2, seats: 70, filled: 58, tuition: 82000, tag: "Weekend",
      about: "Tailored for mid-career managers, focusing on executive decision making and strategic leadership.",
      highlights: ["Executive Strategy", "Operations Management", "Leadership Lab", "Consulting Capstone"] },
  ],

  courses: [
    { code: "CSE-1101", title: "Introduction to Programming", dept: "cse", credits: 3, level: 100, semester: "Fall", prereq: "—", instructor: "Sabina Yasmin", seats: 60, taken: 58 },
    { code: "CSE-2201", title: "Data Structures & Algorithms", dept: "cse", credits: 3, level: 200, semester: "Fall", prereq: "CSE-1101", instructor: "Prof. Dr. Mahmud Hasan", seats: 60, taken: 58 },
    { code: "CSE-2303", title: "Database Systems", dept: "cse", credits: 3, level: 300, semester: "Fall", prereq: "CSE-2201", instructor: "Dr. Tanvir Ahmed", seats: 55, taken: 41 },
    { code: "CSE-3303", title: "Operating Systems", dept: "cse", credits: 3, level: 300, semester: "Spring", prereq: "CSE-2201", instructor: "Dr. Sabbir Rahman", seats: 55, taken: 55 },
    { code: "CSE-4108", title: "Machine Learning & AI", dept: "cse", credits: 3, level: 400, semester: "Fall", prereq: "MAT-2101", instructor: "Dr. Nafisa Haque", seats: 45, taken: 45 },
    { code: "CSE-4210", title: "Distributed Systems", dept: "cse", credits: 3, level: 400, semester: "Spring", prereq: "CSE-3303", instructor: "Prof. Dr. Ayesha Rahman", seats: 40, taken: 27 },
    { code: "EEE-1101", title: "Basic Electrical Engineering", dept: "eee", credits: 3, level: 100, semester: "Fall", prereq: "—", instructor: "Prof. Dr. Kamal Hossain", seats: 60, taken: 52 },
    { code: "EEE-2104", title: "Circuit Analysis II", dept: "eee", credits: 3, level: 200, semester: "Spring", prereq: "EEE-1101", instructor: "Dr. Rubel Mia", seats: 50, taken: 44 },
    { code: "EEE-3301", title: "Power System Engineering", dept: "eee", credits: 3, level: 300, semester: "Fall", prereq: "EEE-2104", instructor: "Prof. Dr. Kamal Hossain", seats: 45, taken: 33 },
    { code: "EEE-4205", title: "VLSI Design", dept: "eee", credits: 3, level: 400, semester: "Spring", prereq: "EEE-2104", instructor: "Dr. Rubel Mia", seats: 35, taken: 19 },
    { code: "CIV-2107", title: "Structural Mechanics", dept: "civ", credits: 3, level: 200, semester: "Fall", prereq: "CIV-1101", instructor: "Dr. Nusrat Jahan", seats: 50, taken: 36 },
    { code: "CIV-3204", title: "Geotechnical Engineering", dept: "civ", credits: 4, level: 300, semester: "Spring", prereq: "CIV-2107", instructor: "Dr. Imran Chowdhury", seats: 40, taken: 28 },
    { code: "BBA-1101", title: "Principles of Management", dept: "bba", credits: 3, level: 100, semester: "Fall", prereq: "—", instructor: "Prof. Dr. Shahriar Kabir", seats: 80, taken: 76 },
    { code: "BBA-3104", title: "Corporate Finance", dept: "bba", credits: 3, level: 300, semester: "Fall", prereq: "BBA-2103", instructor: "Dr. Sharmin Akter", seats: 65, taken: 61 },
    { code: "BBA-3208", title: "Consumer Behaviour", dept: "bba", credits: 3, level: 300, semester: "Spring", prereq: "BBA-1101", instructor: "Dr. Rakib Hasan", seats: 60, taken: 39 },
    { code: "ECO-1101", title: "Principles of Microeconomics", dept: "eco", credits: 3, level: 100, semester: "Fall", prereq: "—", instructor: "Dr. Farhana Islam", seats: 60, taken: 50 },
    { code: "ECO-4103", title: "Applied Econometrics", dept: "eco", credits: 4, level: 400, semester: "Fall", prereq: "MAT-2101", instructor: "Dr. Farhana Islam", seats: 40, taken: 40 },
    { code: "PHY-2201", title: "Quantum Mechanics I", dept: "phy", credits: 3, level: 200, semester: "Fall", prereq: "PHY-1101", instructor: "Prof. Dr. Mahfuz Alam", seats: 40, taken: 22 },
    { code: "PHY-3106", title: "Computational Physics", dept: "phy", credits: 3, level: 300, semester: "Spring", prereq: "PHY-2201", instructor: "Dr. Anisur Rahman", seats: 35, taken: 18 },
    { code: "MAT-1101", title: "Differential & Integral Calculus", dept: "mat", credits: 3, level: 100, semester: "Fall", prereq: "—", instructor: "Dr. Selim Reza", seats: 90, taken: 88 },
    { code: "MAT-2101", title: "Linear Algebra", dept: "mat", credits: 3, level: 200, semester: "Fall", prereq: "MAT-1101", instructor: "Dr. Tanvir Ahmed", seats: 90, taken: 84 },
    { code: "MAT-3204", title: "Numerical Methods", dept: "mat", credits: 3, level: 300, semester: "Spring", prereq: "MAT-2101", instructor: "Dr. Sumaiya Karim", seats: 60, taken: 37 },
    { code: "ENG-1101", title: "English Reading & Composition", dept: "eng", credits: 3, level: 100, semester: "Fall", prereq: "—", instructor: "Dr. Sadia Noor", seats: 75, taken: 70 },
    { code: "ENG-2105", title: "Postcolonial Literature", dept: "eng", credits: 3, level: 200, semester: "Fall", prereq: "ENG-1101", instructor: "Dr. Sadia Noor", seats: 45, taken: 31 },
    { code: "LAW-1101", title: "Jurisprudence & Legal Theory", dept: "law", credits: 3, level: 100, semester: "Fall", prereq: "—", instructor: "Prof. Dr. Rezaul Karim", seats: 50, taken: 45 },
    { code: "LAW-2201", title: "Constitutional Law", dept: "law", credits: 4, level: 200, semester: "Spring", prereq: "LAW-1101", instructor: "Prof. Dr. Rezaul Karim", seats: 50, taken: 29 },
    { code: "PHA-1101", title: "Inorganic Pharmacy", dept: "pha", credits: 3, level: 100, semester: "Fall", prereq: "—", instructor: "Dr. Mitali Saha", seats: 45, taken: 40 },
    { code: "PHA-3105", title: "Pharmacology & Therapeutics", dept: "pha", credits: 4, level: 300, semester: "Fall", prereq: "PHA-1101", instructor: "Dr. Mitali Saha", seats: 40, taken: 38 },
  ],

  faculty: [
    { name: "Prof. Dr. Ayesha Rahman", dept: "cse", role: "Professor & Head", field: "Distributed Systems, Cloud & ML", email: "ayesha.rahman@bidyapith.edu", office: "Sun & Tue, 2–4 PM · Room 512", since: 2009, papers: 47,
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
      bio: "Leads the systems research group and supervises the CSE capstone track. Research fellow in distributed systems." },
    { name: "Prof. Dr. Kamal Hossain", dept: "eee", role: "Professor & Head", field: "Power Systems & Smart Grids", email: "kamal.hossain@bidyapith.edu", office: "Mon & Wed, 11 AM–1 PM · Room 402", since: 2006, papers: 63,
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
      bio: "Advises national grid modernisation committees and directs the renewable microgrid research facility." },
    { name: "Dr. Nusrat Jahan", dept: "civ", role: "Associate Professor & Head", field: "Structural & Earthquake Engineering", email: "nusrat.jahan@bidyapith.edu", office: "Tue & Thu, 10 AM–12 PM · Room 301", since: 2013, papers: 29,
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80",
      bio: "Specialises in earthquake-resilient structures and retrofitting dense urban housing in older metropolitan zones." },
    { name: "Prof. Dr. Shahriar Kabir", dept: "bba", role: "Professor & Dean, Business", field: "Strategic Management & Policy", email: "shahriar.kabir@bidyapith.edu", office: "Sun & Wed, 3–5 PM · Room 204", since: 2004, papers: 51,
      avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80",
      bio: "Dean of the School of Business and architect of the Executive MBA. Senior consultant for top multinational enterprises." },
    { name: "Dr. Farhana Islam", dept: "eco", role: "Associate Professor & Head", field: "Development Economics & Econometrics", email: "farhana.islam@bidyapith.edu", office: "Mon & Thu, 1–3 PM · Room 218", since: 2014, papers: 34,
      avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&auto=format&fit=crop&q=80",
      bio: "Analyzes national survey micro-data on microfinance, labor markets, and gender equity in South Asia." },
    { name: "Prof. Dr. Mahfuz Alam", dept: "phy", role: "Professor & Head", field: "Quantum Optics & Condensed Matter", email: "mahfuz.alam@bidyapith.edu", office: "Tue & Thu, 2–4 PM · Room 109", since: 2007, papers: 58,
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
      bio: "Directs the quantum optics lab and mentors scholars into international doctorate fellowships." },
    { name: "Dr. Sadia Noor", dept: "eng", role: "Associate Professor & Head", field: "Postcolonial Literature & Translation", email: "sadia.noor@bidyapith.edu", office: "Sun & Tue, 11 AM–1 PM · Room 610", since: 2015, papers: 22,
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
      bio: "Translates contemporary South Asian fiction into English and coordinates the annual Bidyapith Literary Symposium." },
    { name: "Prof. Dr. Rezaul Karim", dept: "law", role: "Professor & Head", field: "Constitutional & Administrative Law", email: "rezaul.karim@bidyapith.edu", office: "Wed, 10 AM–1 PM · Room 704", since: 2011, papers: 41,
      avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400&auto=format&fit=crop&q=80",
      bio: "Head coach of the university moot court team and published scholar on constitutional jurisprudence." },
    { name: "Dr. Mitali Saha", dept: "pha", role: "Associate Professor & Head", field: "Clinical Pharmacology & Drug Delivery", email: "mitali.saha@bidyapith.edu", office: "Mon & Wed, 9–11 AM · Room 801", since: 2016, papers: 26,
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80",
      bio: "Oversees clinical pharmacy rotations with top healthcare hospitals and researches antibiotic resistance." },
    { name: "Dr. Tanvir Ahmed", dept: "cse", role: "Associate Professor", field: "Database Systems & Big Data", email: "tanvir.ahmed@bidyapith.edu", office: "Sun & Thu, 2–4 PM · Room 515", since: 2012, papers: 31,
      avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80",
      bio: "Teaches core database systems, indexing techniques, and distributed query engines." },
    { name: "Dr. Nafisa Haque", dept: "cse", role: "Assistant Professor", field: "Machine Learning, NLP & AI", email: "nafisa.haque@bidyapith.edu", office: "Tue & Thu, 3–5 PM · Room 518", since: 2019, papers: 18,
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80",
      bio: "Builds Bengali LLMs and leads research at the AI & Data Science Innovation Lab." },
    { name: "Dr. Sabbir Rahman", dept: "cse", role: "Assistant Professor", field: "Operating Systems & Networking", email: "sabbir.rahman@bidyapith.edu", office: "Mon & Wed, 2–4 PM · Room 520", since: 2020, papers: 14,
      avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80",
      bio: "Kernel scheduling and low-latency network protocol optimization." },
    { name: "Prof. Dr. Mahmud Hasan", dept: "cse", role: "Professor", field: "Theoretical CS & Graph Algorithms", email: "mahmud.hasan@bidyapith.edu", office: "Sun & Tue, 10 AM–12 PM · Room 508", since: 2008, papers: 54,
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
      bio: "ACM ICPC chief coach and author of standard textbooks on competitive graph theory." },
    { name: "Sabina Yasmin", dept: "cse", role: "Lecturer", field: "Software Engineering & Web Technologies", email: "sabina.yasmin@bidyapith.edu", office: "Wed & Thu, 1–3 PM · Room 522", since: 2022, papers: 6,
      avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&auto=format&fit=crop&q=80",
      bio: "Full-stack development, modern web architectures, and student project mentorship." },
    { name: "Dr. Rubel Mia", dept: "eee", role: "Associate Professor", field: "VLSI Design & Semiconductors", email: "rubel.mia@bidyapith.edu", office: "Mon & Thu, 3–5 PM · Room 408", since: 2014, papers: 28,
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80",
      bio: "Custom chip design and low-power ASIC synthesis for telecommunication." },
    { name: "Dr. Farhana Tasnim", dept: "eee", role: "Assistant Professor", field: "Renewable Energy & IoT", email: "farhana.tasnim@bidyapith.edu", office: "Tue & Thu, 11 AM–1 PM · Room 412", since: 2018, papers: 19,
      avatar: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&auto=format&fit=crop&q=80",
      bio: "Solar PV optimization and IoT-driven wireless sensor networks." },
    { name: "Dr. Imran Chowdhury", dept: "civ", role: "Assistant Professor", field: "Geotechnical Engineering", email: "imran.chowdhury@bidyapith.edu", office: "Sun & Wed, 2–4 PM · Room 305", since: 2017, papers: 16,
      avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80",
      bio: "Soil stabilization, deep pile foundations, and slope stability analysis." },
    { name: "Dr. Sharmin Akter", dept: "bba", role: "Associate Professor", field: "Corporate Finance & Capital Markets", email: "sharmin.akter@bidyapith.edu", office: "Mon & Wed, 2–4 PM · Room 210", since: 2018, papers: 24,
      avatar: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&auto=format&fit=crop&q=80",
      bio: "Fintech, trading room simulations, and corporate governance in South Asian bourses." },
    { name: "Dr. Rakib Hasan", dept: "bba", role: "Assistant Professor", field: "Digital Marketing & Analytics", email: "rakib.hasan@bidyapith.edu", office: "Tue & Thu, 10 AM–12 PM · Room 215", since: 2020, papers: 12,
      avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=400&auto=format&fit=crop&q=80",
      bio: "Consumer behavior models and performance analytics in hyper-growth digital startups." },
    { name: "Dr. Selim Reza", dept: "mat", role: "Professor", field: "Linear Algebra & Dynamical Systems", email: "selim.reza@bidyapith.edu", office: "Sun & Tue, 9–11 AM · Room 115", since: 2005, papers: 49,
      avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&auto=format&fit=crop&q=80",
      bio: "Differential equations and dynamical system modeling in biological sciences." },
    { name: "Dr. Sumaiya Karim", dept: "mat", role: "Associate Professor", field: "Numerical Analysis & Optimization", email: "sumaiya.karim@bidyapith.edu", office: "Mon & Thu, 2–4 PM · Room 118", since: 2016, papers: 21,
      avatar: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=400&auto=format&fit=crop&q=80",
      bio: "Convex optimization, finite element analysis, and computational mathematics." },
    { name: "Dr. Anisur Rahman", dept: "phy", role: "Associate Professor", field: "Computational Physics & Nanomaterials", email: "anisur.rahman@bidyapith.edu", office: "Sun & Wed, 11 AM–1 PM · Room 105", since: 2015, papers: 27,
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80",
      bio: "Density functional theory (DFT) simulations of high-efficiency 2D photovoltaic materials." },
    { name: "Dr. Nazmul Huda", dept: "law", role: "Assistant Professor", field: "Corporate Law & Cyber Regulations", email: "nazmul.huda@bidyapith.edu", office: "Tue & Thu, 2–4 PM · Room 708", since: 2019, papers: 15,
      avatar: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400&auto=format&fit=crop&q=80",
      bio: "Data privacy regulations, IP protection, and corporate securities compliance." },
  ],

  notices: [
    { id: 1, title: "Fall 2026 course registration is officially open", date: "2026-09-08", type: "Academic", pinned: true, body: "Registration for Fall 2026 is now open. Please complete advisor clearance before choosing your courses." },
    { id: 2, title: "100 New Student Profiles & 25 Faculty Records Active", date: "2026-09-06", type: "Notice", pinned: true, body: "The university digital repository has been fully seeded with comprehensive department rosters and credentials." },
    { id: 3, title: "Mid-term examination schedule published", date: "2026-09-04", type: "Exam", pinned: false, body: "The mid-term schedule for undergraduate programmes is available on the student portal." },
    { id: 4, title: "Spring 2026 results released", date: "2026-08-28", type: "Result", pinned: false, body: "Grades and semester GPA have been published. Re-scrutiny applications remain open until 10 September." },
    { id: 5, title: "Bidyapith Tech Fest 2026 — Registration Open", date: "2026-08-22", type: "Event", pinned: false, body: "Sign up for hackathon, robotics, and case-solving competitions across campus." },
    { id: 6, title: "Tuition instalment deadline: 20 September", date: "2026-08-18", type: "Payment", pinned: false, body: "Fall 2026 tuition instalment is due. You can pay securely through online gateways or bKash." },
  ],

  events: [
    { title: "Admission Open Day", date: "2026-09-20", place: "Central Auditorium", time: "10:00 AM" },
    { title: "Bidyapith Tech Fest 2026", date: "2026-10-02", place: "Engineering Quad", time: "9:00 AM" },
    { title: "Annual Convocation", date: "2026-11-14", place: "University Ground", time: "3:00 PM" },
    { title: "Research Symposium", date: "2026-11-28", place: "Library Hall", time: "11:00 AM" },
  ],

  admissionSteps: [
    { title: "Create an account", text: "Register with your university email or applicant identity." },
    { title: "Fill in the application", text: "Add academic history, upload transcripts, and select preferred programmes." },
    { title: "Pay the application fee", text: "Pay ৳1,000 securely online through card or mobile banking." },
    { title: "Sit the admission test", text: "Attend the written admission test followed by department viva." },
    { title: "Confirm your seat", text: "Accept admission offer and receive your university student ID." },
  ],

  keyDates: [
    { label: "Application opens", date: "20 August 2026", status: "done" },
    { label: "Application closes", date: "15 October 2026", status: "live" },
    { label: "Admission test", date: "25 October 2026", status: "next" },
    { label: "Results published", date: "05 November 2026", status: "next" },
    { label: "Seat confirmation", date: "15 November 2026", status: "next" },
    { label: "Classes begin", date: "01 December 2026", status: "next" },
  ],

  fees: [
    { program: "B.Sc. in Computer Science & Engineering", admission: 25000, perCredit: 4500, semester: 68000, total: 1116000 },
    { program: "B.Sc. in Electrical & Electronic Engineering", admission: 25000, perCredit: 4200, semester: 66000, total: 1084000 },
    { program: "B.Sc. in Civil Engineering", admission: 25000, perCredit: 4000, semester: 64000, total: 1052000 },
    { program: "Bachelor of Business Administration", admission: 20000, perCredit: 3800, semester: 58000, total: 884000 },
    { program: "LL.B. (Honours)", admission: 20000, perCredit: 4000, semester: 52000, total: 812000 },
    { program: "Bachelor of Pharmacy (Professional)", admission: 30000, perCredit: 4800, semester: 74000, total: 1420000 },
  ],

  scholarships: [
    { name: "Merit award", cover: "Up to 100%", who: "GPA 5.00 in both SSC and HSC, or CGPA 3.90+ at Bidyapith.", accent: "jade" },
    { name: "Need-based grant", cover: "25–60%", who: "Assessed on family income with verified documentation.", accent: "gold" },
    { name: "Freedom fighter quota", cover: "50%", who: "Children and grandchildren of certified freedom fighters.", accent: "orchid" },
    { name: "Sibling & alumni waiver", cover: "15%", who: "A sibling currently enrolled, or parent who graduated.", accent: "rose" },
  ],

  faqs: [
    { q: "Can I apply to more than one programme?", a: "Yes. You may list up to three programmes in order of preference on a single application." },
    { q: "How do I pay tuition fees?", a: "From the student portal, through bKash, card, or direct bank transfer." },
    { q: "Can I transfer credits from another university?", a: "Up to 40% of credits can be transferred upon department review." },
    { q: "Is there campus accommodation?", a: "Yes, dedicated male and female residential halls located on campus." },
  ],

  voices: [
    { name: "Rifat Chowdhury", meta: "CSE, Class of 2025 · Engineer at Brain Station 23", quote: "The capstone project and faculty mentorship prepared me directly for industry leadership.", av: 1 },
    { name: "Anika Tabassum", meta: "BBA Finance, Class of 2024 · Analyst at IDLC", quote: "Digital registration and Bloomberg lab access made our coursework genuinely cutting-edge.", av: 2 },
    { name: "Shakib Al Noman", meta: "LL.B., Class of 2026 · Moot Court Captain", quote: "Our moot team reached the national finals under the direct coaching of senior faculty.", av: 3 },
  ],

  milestones: [
    { year: "1998", title: "Bidyapith founded", text: "Started with two faculties and 240 passionate students." },
    { year: "2005", title: "Purbachal Permanent Campus", text: "Relocated to a custom-designed 22-acre modern university campus." },
    { year: "2012", title: "Graduate Research School", text: "Inaugurated Master's degrees in Engineering and Business." },
    { year: "2019", title: "Centre for Applied Research", text: "Established national and international research labs." },
    { year: "2026", title: "Unified Digital Campus System", text: "Connected admissions, registration, grading, and finances into one unified platform." },
  ],

  leadership: [
    { name: "Prof. Dr. Anwar Hossain", role: "Vice-Chancellor", note: "Physicist with twenty-two years of distinguished academic leadership.", av: 1 },
    { name: "Prof. Dr. Shahriar Kabir", role: "Pro Vice-Chancellor", note: "Dean of Business and architect of the Executive MBA.", av: 2 },
    { name: "Md. Jahangir Alam", role: "Registrar", note: "Oversees academic calendar, admissions, and student records.", av: 3 },
    { name: "Dr. Farzana Rahman", role: "Dean of Students", note: "Coordinates halls, student organizations, and wellness services.", av: 4 },
  ],
};
